In [43]:
import numpy as np

# X - Restaurants x Users
# Each row corresponds to user vector
X = np.asarray([[5,5,0,0],[5,0,0,0],[0,4,0,0],[0,0,5,4],[0,0,5,0]])

# Y is Feature vector of all restaurants. One row is a single feature vector
# of one restaurant. Number of features = 2
Y = np.transpose(np.asarray(
[[ 0.9, 0 ],
 [ 1, 0.01],
 [ 0.99 , 0],
 [ 0.1  , 1],
 [ 0   ,0.9]]))

print Y
print X
# print np.random.randn(10) #y
# print np.random.randn(10, 5) #x

[[ 0.9   1.    0.99  0.1   0.  ]
 [ 0.    0.01  0.    1.    0.9 ]]
[[5 5 0 0]
 [5 0 0 0]
 [0 4 0 0]
 [0 0 5 4]
 [0 0 5 0]]


In [44]:
# Running gradient descent on one feature of business
from sklearn import linear_model

model = linear_model.SGDRegressor()
# Here Y[0] indicates one feature of the business.
model.fit(X, Y[0])


SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', n_iter=5, penalty='l2', power_t=0.25,
       random_state=None, shuffle=True, verbose=0, warm_start=False)

In [45]:
# Our parameters needed

model.coef_

array([ 0.11389222,  0.10094335,  0.00114642,  0.00655039])